sudo: required
dist: trusty

language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git2cl gtk-doc-tools w3-dtd-mathml libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-tools gstreamer1.0-plugins-base

compiler:
  - clang
  - gcc

env:
  - GSTVERSION=1.0

script: ./autogen.sh && ./configure --enable-gtk-doc --enable-man --with-gstreamer=${GSTVERSION} && make && make check && make distcheck

after_failure: cat src/test-suite.log

notifications:
  email: false
